include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

variables:
  DD_IMAGE_NAME: traefik
  DD_IMAGE_TAG: v1.7
  STACK: gateway

.deploy:
  variables:
    SERVICES_TO_CHECK: ${STACK}_${CI_PROJECT_NAME}
  environment:
    url: https://${CI_PROJECT_NAME}.${PUBLIC_HOSTNAME}
